version: '3.9'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    volumes:
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/dbinit.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    build: ./
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    restart: always
volumes:
  postgres_data:
